version: "3.9"

services:
  db:
    image: postgres:15
    container_name: focusboard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: focusboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: focusboard-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./focusboard-frontend
      dockerfile: Dockerfile
    container_name: focusboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  postgres_data:
