"""Add style field for userwidget

Revision ID: abf27b8ee8f5
Revises: 35ff0e05c44e
Create Date: 2025-07-24 21:19:40.821525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf27b8ee8f5'
down_revision: Union[str, Sequence[str], None] = '35ff0e05c44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_widget_unique'), 'user_widgets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_widget_unique'), 'user_widgets', ['user_id', 'widget_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
